name: Build Electron App (Windows)

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Electron Forge Make (Windows only)
        run: npx electron-forge make --targets @electron-forge/maker-squirrel

      - name: Upload Windows installer to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/squirrel.windows/x64/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
