name: Build Electron App (.deb)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Linux packaging dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg fakeroot

      - name: Run Electron Forge Make (deb only)
        run: npx electron-forge make --targets @electron-forge/maker-deb

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/make/deb/x64/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
